server.port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

  client:
    service-url.defaultZone: http://127.0.0.1:9999/eureka/
