server.port: 8889

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lavcraft/configproperties.git

eureka.client.service-url.defaultZone: http://127.0.0.1:9999/eureka/
spring.application.name: CONFIGSERVER
